import type { TrainingResource } from '../types'

type TrainingMap = Record<string, TrainingResource>

export const TRAINING_MAP: TrainingMap = {
  python: {
    courseraUrl: 'https://www.coursera.org/specializations/python',
    udemyUrl: 'https://www.udemy.com/course/complete-python-bootcamp/',
    certification: '',
    certUrl: '',
    estimatedHours: 40,
  },
  sql: {
    courseraUrl: 'https://www.coursera.org/learn/sql-for-data-science',
    udemyUrl: 'https://www.udemy.com/course/the-complete-sql-bootcamp/',
    certification: '',
    certUrl: '',
    estimatedHours: 30,
  },
  spark: {
    courseraUrl: 'https://www.coursera.org/learn/apache-spark-sql-for-data-analysts',
    udemyUrl: 'https://www.udemy.com/course/taming-big-data-with-apache-spark-hands-on/',
    certification: 'Databricks Certified Associate Developer',
    certUrl: 'https://www.databricks.com/learn/certification/apache-spark-developer-associate',
    estimatedHours: 60,
  },
  tensorflow: {
    courseraUrl: 'https://www.coursera.org/specializations/tensorflow-in-practice',
    udemyUrl: 'https://www.udemy.com/course/complete-guide-to-tensorflow-for-deep-learning-with-python/',
    certification: 'Google TensorFlow Developer Certificate',
    certUrl: 'https://www.tensorflow.org/certificate',
    estimatedHours: 80,
  },
  pytorch: {
    courseraUrl: 'https://www.coursera.org/learn/deep-neural-networks-with-pytorch',
    udemyUrl: 'https://www.udemy.com/course/pytorch-for-deep-learning-and-computer-vision/',
    certification: '',
    certUrl: '',
    estimatedHours: 60,
  },
  'scikit-learn': {
    courseraUrl: 'https://www.coursera.org/learn/machine-learning-with-python',
    udemyUrl: 'https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/',
    certification: '',
    certUrl: '',
    estimatedHours: 40,
  },
  pandas: {
    courseraUrl: 'https://www.coursera.org/search?query=pandas+python',
    udemyUrl: 'https://www.udemy.com/course/data-analysis-with-pandas/',
    certification: '',
    certUrl: '',
    estimatedHours: 20,
  },
  numpy: {
    courseraUrl: 'https://www.coursera.org/search?query=numpy+python',
    udemyUrl: 'https://www.udemy.com/course/deep-learning-prerequisites-the-numpy-stack-in-python/',
    certification: '',
    certUrl: '',
    estimatedHours: 15,
  },
  docker: {
    courseraUrl: 'https://www.coursera.org/search?query=docker+containers',
    udemyUrl: 'https://www.udemy.com/course/docker-mastery/',
    certification: 'Docker Certified Associate',
    certUrl: 'https://training.mirantis.com/certification/dca-certification-exam/',
    estimatedHours: 35,
  },
  kubernetes: {
    courseraUrl: 'https://www.coursera.org/learn/google-kubernetes-engine',
    udemyUrl: 'https://www.udemy.com/course/certified-kubernetes-administrator-with-practice-tests/',
    certification: 'CKA (Certified Kubernetes Administrator)',
    certUrl: 'https://training.linuxfoundation.org/certification/certified-kubernetes-administrator-cka/',
    estimatedHours: 60,
  },
  airflow: {
    courseraUrl: 'https://www.coursera.org/search?query=apache+airflow',
    udemyUrl: 'https://www.udemy.com/course/the-complete-hands-on-course-to-master-apache-airflow/',
    certification: '',
    certUrl: '',
    estimatedHours: 25,
  },
  dbt: {
    courseraUrl: 'https://courses.getdbt.com/courses/fundamentals',
    udemyUrl: 'https://www.udemy.com/course/complete-dbt-data-build-tool-bootcamp-zero-to-hero-learn-dbt/',
    certification: 'dbt Analytics Engineering Certification',
    certUrl: 'https://www.getdbt.com/certifications/analytics-engineer-certification/',
    estimatedHours: 30,
  },
  snowflake: {
    courseraUrl: 'https://www.coursera.org/search?query=snowflake+data+warehouse',
    udemyUrl: 'https://www.udemy.com/course/snowflake-masterclass/',
    certification: 'SnowPro Core Certification',
    certUrl: 'https://www.snowflake.com/certifications/',
    estimatedHours: 35,
  },
  databricks: {
    courseraUrl: 'https://www.coursera.org/search?query=databricks',
    udemyUrl: 'https://www.udemy.com/course/databricks-certified-associate-developer-for-apache-spark/',
    certification: 'Databricks Certified Data Engineer Associate',
    certUrl: 'https://www.databricks.com/learn/certification/data-engineer-associate',
    estimatedHours: 50,
  },
  aws: {
    courseraUrl: 'https://www.coursera.org/specializations/aws-machine-learning',
    udemyUrl: 'https://www.udemy.com/course/aws-machine-learning/',
    certification: 'AWS Certified Machine Learning Specialty',
    certUrl: 'https://aws.amazon.com/certification/certified-machine-learning-specialty/',
    estimatedHours: 120,
  },
  gcp: {
    courseraUrl: 'https://www.coursera.org/specializations/machine-learning-engineering-for-production-mlops',
    udemyUrl: 'https://www.udemy.com/course/google-cloud-professional-machine-learning-engineer-certification/',
    certification: 'Google Professional ML Engineer',
    certUrl: 'https://cloud.google.com/certification/machine-learning-engineer',
    estimatedHours: 100,
  },
  azure: {
    courseraUrl: 'https://www.coursera.org/specializations/azure-data-scientist',
    udemyUrl: 'https://www.udemy.com/course/dp100-azure/',
    certification: 'Azure AI Engineer Associate (AI-102)',
    certUrl: 'https://learn.microsoft.com/en-us/certifications/azure-ai-engineer/',
    estimatedHours: 80,
  },
  mlflow: {
    courseraUrl: 'https://www.coursera.org/search?query=mlflow',
    udemyUrl: 'https://www.udemy.com/course/mlflow-course/',
    certification: '',
    certUrl: '',
    estimatedHours: 20,
  },
  mlops: {
    courseraUrl: 'https://www.coursera.org/specializations/machine-learning-engineering-for-production-mlops',
    udemyUrl: 'https://www.udemy.com/course/mlops-with-mlflow-and-azure-databricks/',
    certification: '',
    certUrl: '',
    estimatedHours: 60,
  },
  'feature-store': {
    courseraUrl: 'https://www.coursera.org/search?query=feature+store+mlops',
    udemyUrl: 'https://www.udemy.com/course/feature-store-for-machine-learning/',
    certification: '',
    certUrl: '',
    estimatedHours: 15,
  },
  llm: {
    courseraUrl: 'https://www.coursera.org/specializations/large-language-models',
    udemyUrl: 'https://www.udemy.com/course/llm-engineering-master-ai-and-large-language-models/',
    certification: '',
    certUrl: '',
    estimatedHours: 50,
  },
  rag: {
    courseraUrl: 'https://www.coursera.org/search?query=retrieval+augmented+generation',
    udemyUrl: 'https://www.udemy.com/course/rag-retrieval-augmented-generation-masterclass/',
    certification: '',
    certUrl: '',
    estimatedHours: 25,
  },
  langchain: {
    courseraUrl: 'https://www.coursera.org/search?query=langchain',
    udemyUrl: 'https://www.udemy.com/course/langchain/',
    certification: '',
    certUrl: '',
    estimatedHours: 20,
  },
  transformers: {
    courseraUrl: 'https://www.coursera.org/specializations/natural-language-processing',
    udemyUrl: 'https://www.udemy.com/course/nlp-with-transformers/',
    certification: '',
    certUrl: '',
    estimatedHours: 50,
  },
  'computer-vision': {
    courseraUrl: 'https://www.coursera.org/specializations/deep-learning',
    udemyUrl: 'https://www.udemy.com/course/pytorch-for-deep-learning-and-computer-vision/',
    certification: '',
    certUrl: '',
    estimatedHours: 60,
  },
  nlp: {
    courseraUrl: 'https://www.coursera.org/specializations/natural-language-processing',
    udemyUrl: 'https://www.udemy.com/course/nlp-natural-language-processing-with-python/',
    certification: '',
    certUrl: '',
    estimatedHours: 50,
  },
  statistics: {
    courseraUrl: 'https://www.coursera.org/specializations/statistics-with-python',
    udemyUrl: 'https://www.udemy.com/course/statistics-for-data-science-and-business-analysis/',
    certification: '',
    certUrl: '',
    estimatedHours: 40,
  },
  'deep-learning': {
    courseraUrl: 'https://www.coursera.org/specializations/deep-learning',
    udemyUrl: 'https://www.udemy.com/course/complete-deep-learning/',
    certification: '',
    certUrl: '',
    estimatedHours: 100,
  },
  'data-pipeline': {
    courseraUrl: 'https://www.coursera.org/search?query=data+pipeline+etl',
    udemyUrl: 'https://www.udemy.com/course/data-engineering-essentials-sql-python-and-spark/',
    certification: '',
    certUrl: '',
    estimatedHours: 40,
  },
  tableau: {
    courseraUrl: 'https://www.coursera.org/specializations/data-visualization',
    udemyUrl: 'https://www.udemy.com/course/tableau10/',
    certification: 'Tableau Desktop Specialist',
    certUrl: 'https://www.salesforce.com/products/tableau/tableau-certification/',
    estimatedHours: 30,
  },
  kafka: {
    courseraUrl: 'https://www.coursera.org/search?query=apache+kafka',
    udemyUrl: 'https://www.udemy.com/course/apache-kafka/',
    certification: 'Confluent Certified Developer',
    certUrl: 'https://www.confluent.io/certification/',
    estimatedHours: 40,
  },
  terraform: {
    courseraUrl: 'https://www.coursera.org/search?query=terraform+infrastructure',
    udemyUrl: 'https://www.udemy.com/course/terraform-beginner-to-advanced/',
    certification: 'HashiCorp Terraform Associate',
    certUrl: 'https://www.hashicorp.com/certifications/terraform-associate',
    estimatedHours: 40,
  },
  git: {
    courseraUrl: 'https://www.coursera.org/learn/introduction-git-github',
    udemyUrl: 'https://www.udemy.com/course/git-complete/',
    certification: '',
    certUrl: '',
    estimatedHours: 15,
  },
  scala: {
    courseraUrl: 'https://www.coursera.org/specializations/scala',
    udemyUrl: 'https://www.udemy.com/course/rock-the-jvm-scala-for-beginners/',
    certification: '',
    certUrl: '',
    estimatedHours: 60,
  },
  r: {
    courseraUrl: 'https://www.coursera.org/specializations/statistics',
    udemyUrl: 'https://www.udemy.com/course/r-programming/',
    certification: '',
    certUrl: '',
    estimatedHours: 40,
  },
}

export function getTraining(skill: string): TrainingResource {
  return TRAINING_MAP[skill] ?? {
    courseraUrl: `https://www.coursera.org/search?query=${encodeURIComponent(skill)}`,
    udemyUrl: `https://www.udemy.com/courses/search/?q=${encodeURIComponent(skill)}`,
    certification: '',
    certUrl: '',
    estimatedHours: 30,
  }
}
